### ISSUE TITLE
Warning message for untagged projects is misleading

### ISSUE THREAD

**Issue by Dispader** [Dispader/manifesto#33]
For untagged, but Git-controlled, projects, the plugin issues a warning at load:

> `warning: The Manifesto plugin is only useful for projects using git source control.`

Which is true, but horribly misleading.

As I see it, our options are:
1. Report a different error message, complaining that Manifesto is also useless without a base tag.
2. Default the version to 0.0.0 (possibly warning folks that this will be the only calculated version).
3. Force the Git client to calculate the base drift from the initial commit.
4. Have Manifesto locally tag the base commit, encouraging the user to start SemVerring with tags.

Umm... @cdinger ... help?  :)

**Comment by cdinger** [comment]
Semver recommends starting at 0.1.0 (http://semver.org/#faq). But if there's nothing there, I think it'd be best to throw a warning—something like:

> warning: The Manifesto plugin couldn't find any version tags. Create your first version with `git tag v0.1.0`.

...or something like that. Thoughts?

**Comment by Dispader** [comment]
I like it!  Should we try to hook the warning to when folks try to run tasks which specifically benefit from Manifesto (right now, `jar` and `war`)?

(I noticed that we warn now on project configuration (at the very start of whatever tasks, even `gradle tasks`), which can scroll off depending on output.

**Comment by Dispader** [comment]
Fixed in e1bcc7456df27c455fb8ce8272eb4fc7d9ee907e
