### ISSUE TITLE
Question/suggestion: extend existing jar/war tasks?

### ISSUE THREAD

**Issue by cdinger** [Dispader/manifesto#8]
It'd be awesome if manifesto hooked onto the existing jar/war tasks so if I load the plugin, it'll just silently populate a manifest using my existing tasks/workflow.

Thoughts?

**Comment by cdinger** [comment]
This seems to implement the suggestion:

```gradle
// manifesto.gradle

buildscript {
    repositories.jcenter()
    dependencies.classpath 'org.ajoberstar:grgit:1.7.0'
}

class Version {
    static describe() {
        try {
            def git = org.ajoberstar.grgit.Grgit.open()
            git.describe() ?: git.head().abbreviatedId
        } catch (Exception e) {
            'unknown'
        }

    }
}

if (project.tasks.findByPath('jar') ) {
    jar {
        manifest {
            attributes('Implementation-Version': Version.describe(),
                       'Implementation-Timestamp': new Date())
        }
    }
}

if (project.tasks.findByPath('war') ) {
    war {
        manifest {
            attributes('Implementation-Version': Version.describe(),
                       'Implementation-Timestamp': new Date())
        }
    }
}
```
That'll silently provide a manifest for jars/wars (or silently do nothing if the java or war plugins aren't present).

How to make this a standalone jar plugin? No idea...

**Comment by Dispader** [comment]
@cdinger Excellent! (!!)  I've actually already got a local branch that makes it a standalone JAr Plugin, but hadn't yet found out how to extend the `jar` and `war` tasks.

I'll push up the dirty branch and add this code.

**Comment by Dispader** [comment]
Here's the "dirty" commit over on https://github.com/Dispader/manifesto/tree/implement_standalone_plugin : ad36ab71ed29e5d020f581f2ae6782becfe3a2cc

Biggest not-solved problem right now is that it "uploads" the Plugin JAr to a Maven "repo" which is at `../repo`.

**Comment by Dispader** [comment]
It appears that loading the Manifesto plugin before* loading the Java plugin fails to add manifest information to the JAr (as the jar isn't around before the plugin gets loaded).

Still not sure how to solve this problem, but would welcome any help.

**Comment by Dispader** [comment]
...and I think I found some folks with a similar problem [here](http://blog.danlew.net/2015/04/27/victor/).

> Evaluating Extensions
Victor comes with a `victor {}` closure which lets you configure the plugin. This is known as an extension. While it makes end-user configuration easy, it proved tricky to use due to the order of execution.

> Roughly, these are the steps for adding Victor to a project:

> Use `project.apply()` to add the Victor plugin.
   - The plugin adds a configurable extension, `victor {}`.
   - The plugin configures its tasks with variables from the extension.
   - End-users can now create their own `victor {}` configuration.

> This flow creates a catch-22 because we have to apply the plugin all at once. Users can't create the `victor {}` block until the plugin is applied, but then that means the plugin can't use that information until after the plugin is done with configuration.

> The solution to this problem is `project.afterEvaluate`. The code inside the closure is executed after the inital evaluation of the project, so you can use variables from the extension.

**Comment by Dispader** [comment]
Well, this is damned peculiar.  The `afterEvaluate` block doesn't seem to be executing.
